"""Initial courses tables

Revision ID: 1335f825388c
Revises: bfef2a1e6571
Create Date: 2025-08-14 22:34:37.105387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1335f825388c'
down_revision: Union[str, Sequence[str], None] = 'bfef2a1e6571'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('video_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'video_url')
    # ### end Alembic commands ###
