"""order step

Revision ID: 0bdbf3580980
Revises: 7fd37bc05a9c
Create Date: 2025-08-19 01:56:25.148563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0bdbf3580980'
down_revision: Union[str, Sequence[str], None] = '7fd37bc05a9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('order', sa.Integer(), default=0))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('steps', 'order')
    # ### end Alembic commands ###
