"""Is complited user progress

Revision ID: c7d0be7e517a
Revises: 0bdbf3580980
Create Date: 2025-08-21 10:38:29.920683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c7d0be7e517a'
down_revision: Union[str, Sequence[str], None] = '0bdbf3580980'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('steps', 'order',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('usercourseprogresss', sa.Column('is_completed', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('usercourseprogresss', 'is_completed')
    op.alter_column('steps', 'order',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
